# 선형대수학 클린업 1주차 코드(파이썬)

In [1]:
import numpy as np

# 벡터뿌시기!

### 원소를 1,2,3으로 하는 벡터를 만들어 봅시다.

In [2]:
x1= np.array([1,2,3])
print(x1)

[1 2 3]


### 원소를 1~9로 하는 벡터를 만들어 봅시다.

In [3]:
x2= np.arange(1,10,dtype=np.int)
print(x2)

[1 2 3 4 5 6 7 8 9]


### 원소의 데이터 타입으로 a정수, b실수, c문자열을 부여해봅시다.

In [4]:
print(np.array(x1,np.int)) #정수
print(np.array(x1,np.float)) #실수
print(np.array(x1,np.str)) #문자열

[1 2 3]
[1. 2. 3.]
['1' '2' '3']


### 벡터의 type, 차원, 원소개수를 확인해봅시다.

In [5]:
print(x1)
print(x1.dtype) #원소타입
print(type(x1))
print(x1.ndim) #차원
print(x1.shape) #다차원형태
print(x1.size) #원소개수

[1 2 3]
int32
<class 'numpy.ndarray'>
1
(3,)
3


### 논리연산자로 벡터를 필터링해봅시다. 
##### (True,False,True)

In [6]:
print(x1)

#인덱스 이용하기
index=[True,False,True]
print(x1[index])


#getiem 이용하기
print(x1.__getitem__([True,False,True]))

[1 2 3]
[1 3]
[1 3]


### x2의 짝수 원소를 0으로 바꿔봅시다

In [7]:
#구체적인 위치정보 이용하기
x2= np.arange(1,10,dtype=np.int)
print(x2)

x2[[1,3,5,7]] = 0
print(x2)

[1 2 3 4 5 6 7 8 9]
[1 0 3 0 5 0 7 0 9]


In [8]:
#논리연산자 인덱스 이용하기
x2= np.arange(1,10,dtype=np.int)
print(x2)

index=[False,True,False,True,False,True,False,True,False]
x2[index]=0
print(x2)

[1 2 3 4 5 6 7 8 9]
[1 0 3 0 5 0 7 0 9]


### 벡터 연산을 해봅시다. (합, 스칼라곱)

In [9]:
print(x1)

x2=x1*3 #상수배
print(x2)
print(x1+x2) #크기가 같은 두 벡터의 합

[1 2 3]
[3 6 9]
[ 4  8 12]


### +조건으로 필터링해봅시다

In [10]:
print(x2)

print(x2[x2<5]) #5미만인 원소만 필터링

print(sum(x2==6)) #6인 원소 개수세기

[3 6 9]
[3]
1


# 행렬 뿌시기!

### 원소를 1~12로 하는 3x4 행렬을 만들어 봅시다.

In [11]:
y1 = np.arange(1,13).reshape(3, 4)
print(y1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### 행렬의 type, 차원, 원소개수를 확인해봅시다

In [12]:
print(y1)
print(type(y1)) #type
print(y1.dtype)
print(y1.ndim) #차원
print(y1.shape)
print(y1.size) #원소개수

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>
int32
2
(3, 4)
12


### 논리연산자로 행렬을 필터링해봅시다.

In [13]:
print(y1)

#짝수 필터링 인덱스 만들기
idx=(y1%2==0) #2로 나눴을때 나머지가 0
print(idx)


print(y1[idx])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[False  True False  True]
 [False  True False  True]
 [False  True False  True]]
[ 2  4  6  8 10 12]


### y1에서 3의 배수를 -10으로 바꿔봅시다.

In [14]:
print(y1)

idx2=(y1%3==0) #3로 나눴을때 나머지가 0
y1[idx2] = y1[idx2]-10
print(y1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2 -7  4]
 [ 5 -4  7  8]
 [-1 10 11  2]]


### 행렬 연산을 해봅시다.

In [15]:
y2 = np.arange(1,5).reshape(2, 2)
print(y2)

#스칼라배
y3=y2*3
print(y3)

#행렬합
print(y2+y3)

#행렬 원소끼리 곱
print(y2 * y3)

#행렬곱
print(y2.dot(y3))

#전치
print(np.transpose(y2))

#역행렬
print(np.linalg.inv(y2))

[[1 2]
 [3 4]]
[[ 3  6]
 [ 9 12]]
[[ 4  8]
 [12 16]]
[[ 3 12]
 [27 48]]
[[21 30]
 [45 66]]


### + 특정행, 특정열 선택하기

In [16]:
y1 = np.arange(1,13).reshape(3, 4)
print(y1)

print(y1[1]) #두번째 행 추출

print(y1[:,0]) #첫번째 열 추출

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8]
[1 5 9]


# x+2y=3, 3x+4y=5 연립방정식의 해를 풀어봅시다

In [17]:
a=np.array([[1,2],[3,4]])
b=np.array([3,5])
print( np.linalg.solve(a,b) )

[-1.  2.]
